/**
 * Generated by PluginGenerator 0.14.0 from webgme on Sun Nov 22 2015 20:42:03 GMT-0600 (Central Standard Time).
 */

define([], function () {
    'use strict';
    return {
        'Consumer': '/755887987',
        'FCO': '/1',
        'MobileAppData': '/506081609',
        'OrderdingBuffer': '/443034779',
        'OrderedShardFlow': '/1314841779',
        'PartitionKey': '/1442538484',
        'PartitionKeyGenerator': '/1402480414',
        'RawDataFlow': '/1366246755',
        'SampledDataFlow': '/1456662058',
        'SamplingBuffer': '/1014150840',
        'ShardFlow': '/1630095173',
        'ShardProducer': '/1840661588',
        'StreamFlow': '/1806691820',
        'StreamPreProcessor': '/590379363',
        'StreamProducer': '/2146601267',
        'TaggedStream': '/991406852',
    };
});